POST  http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "jeanlouis@gmail.com",
    "password": "coucoutoi1"
}


#######

GET http://localhost:3000/api/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTYyNzI4OTA3NywiZXhwIjoxNjI3Mzc1NDc3fQ.BkI0JDCFjHX5HxLNJycqNxy19o8DSNM3TXwQtoddnQY


######

PUT http://localhost:3000/api/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTYyNzI4OTA3NywiZXhwIjoxNjI3Mzc1NDc3fQ.BkI0JDCFjHX5HxLNJycqNxy19o8DSNM3TXwQtoddnQY
content-type: application/json

{
    "comment: on change tout ça"
}

#####

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "davidcinq@gmail.com",
    "password": "123456"
}

########
DELETE  http://localhost:3000/api/messages/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGUyZmU0ZDI5Y2U0YTBjNjBiNDY2ODAiLCJpYXQiOjE2MjYwNzg0OTUsImV4cCI6MTYyNjE2NDg5NX0.RJzRZRqECpeurQYSB-1TKu-PrcS4v_Nv_FOLLXLRF-k
