POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "marius@gmail.com",
    "password": "saluttoi1"
}


#######

GET http://localhost:3000/api/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyNzkwNTk3NiwiZXhwIjoxNjI3OTkyMzc2fQ.RLKPr-G6tCAkL57aTTYbzHh2Tit-sxDavyTB5864jGs


######

POST http://localhost:3000/api/comments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyNzY1MDQ1MSwiZXhwIjoxNjI3NzM2ODUxfQ.q5f1mhYrOUHx_NY0ShXKEc22Cgj3uVkJwkUYg_cHf6k
content-type: application/json

{
    "comment": "nouvelle modif2"
}

#####

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "linette@gmail.com",
    "password": "saluttoi1"
}

########
PUT http://localhost:3000/api/users/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTYyNzg1NjkzNywiZXhwIjoxNjI3OTQzMzM3fQ.vG9oInUmfN7tH0diC_h61dKI8O18kuIt8mWYykJmbFk
content-type: application/json

{
    "name": "jacques"
}
#####
DELETE http://localhost:3000/api/messages/4
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyNzkwNTk3NiwiZXhwIjoxNjI3OTkyMzc2fQ.RLKPr-G6tCAkL57aTTYbzHh2Tit-sxDavyTB5864jGs
