POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "aurevoir1"
}


#######

GET http://localhost:3000/api/message


######

PUT http://localhost:3000/api/message


